### PR TITLE
github-merge: Use format strings to fix TypeError exception

### PR DESCRIPTION
**Pull request by MarcoFalke**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Haven't tested this, but steps to reproduce are:

```
$ ghm 23027
...
  File "github-merge.py", line 352, in main
    print("ERROR: Cannot find merge of pull request {} on {}." % (pull_reference,host_repo_from), file=stderr)
TypeError: not all arguments converted during string formatting

**Review by fanquake — COMMENTED** [review]
> Haven't tested this, but steps to reproduce are:

I don't see this issue locally (using the merge script at 9b170576be4e5c4c674723625fe411b9c048a1de, and Python 3.6). But ACK migrating to f-strings. If we are going to do this do you just want to convert the whole script to using them?

**Comment by MarcoFalke** [comment]
The offending line is `"ERROR: Cannot find merge of pull request {} on {}." % (pull_reference,host_repo_from)`.

Minimized this gives:

```py
>>> "ERROR: {} on {}." % (1,2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: not all arguments converted during string formatting

**Comment by MarcoFalke** [comment]
Going to leave the other `.format` for now, because they are more tricky to convert than the %s error strings

**Review by fanquake — APPROVED** [review]
ACK b6c26dbad9e243c028eb5e0082264650b7117146

**Pull request merged**
