### PR TITLE
github-merge.py: include lowercase ACKs

### PR DESCRIPTION
**Pull request by fanquake**
i.e https://github.com/bitcoin/bitcoin/pull/20763#pullrequestreview-558711659.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ack

**Comment by MarcoFalke** [comment]
Tend to NACK. Holding down the shift key for three letters shouldn't be too much to ask, given that review is much more expensive than typing an ACK.

Unless I am mistaken this will also incorrectly include review lines such as:

"Would be nice if the icon was black in 4288c8028f1b9f8256f501bb2ae7135e97310bb0"

**Comment by laanwj** [comment]
i agree with @MarcoFalke here i'm notoriously bad at holding the shift key but it seems worth the overhead here for disambiguation

**Comment by jonatack** [comment]
Seems the ack would need to be at the start of a line or with a preceding space but that might not be reliable enough against false positives.

**Pull request closed without merging**
