### PR TITLE
Check for successful runs of all checks

### PR DESCRIPTION
**Pull request by fjahr**
Note: This is just a rough draft and the code does currently not work as the [Github checks API is only available in preview mode](https://developer.github.com/v3/checks/runs/#list-check-runs-for-a-specific-ref). It just supports the discussion on the issue.

Background: Among all the Travis shenanigans the last two days I noticed that one of my PRs did not run the Travis check at all. However, when Appveyor succeeded [the PR appeared to be ready to merge, since all checks passed](https://imgur.com/a/Jb0oj45). I am not sure if it could have actually been merged at this point but the Github UI definitely suggests it and that seems to be easy to miss. A few hours later when Travis came back it appears that the Travis check ran then.

Through the Github checks API it would be possible to check that all checks have run and passed. The code here is just a rough draft of how this can work. At the moment the checks API appears to not respond with any actual data.

### CODE REVIEW

**Comment by fanquake** [comment]
I'm not really keen on my ability to merge anything being dependent on Travis or Appveyor passing. As we've seen in the past, they can and do fail for all sorts of random reasons, like the s390x build running out of disk space.

Maintainers should be compiling and then running unit/functional tests themselves (across 1 or more platforms) themselves before merging anything, and not reliant on CI.

**Comment by fjahr** [comment]
> Maintainers should be compiling and then running unit/functional tests themselves (across 1 or more platforms) themselves before merging anything, and not reliant on CI.

Sure, it could just be a warning but if maintainers don't rely on CI then I will just close it.

**Comment by laanwj** [comment]
It would be ok to do this and just warn, but agree the eventual decision
must be up to the maintainer.

**Comment by MarcoFalke** [comment]
Slightly tend to NACK. Sending more http requests is going to make the script longer code-wise and more fragile (bugs, maintenance overhead or just plain http timeouts). Our ci systems tend to fail rather often and the red check mark that is displayed on GitHub is sufficient to convey this to maintainers (at least to me). Not sure if all the extra code is worth it to duplicate the red check mark in the CLI when merging.

**Comment by fjahr** [comment]
> [...] the red check mark that is displayed on GitHub is sufficient to convey this to maintainers (at least to me).

That was the main question to me: is it possible that there will be no red checkmark as in my [screenshot](https://imgur.com/a/Jb0oj45) and then it could be overlooked that a check did not run. Otherwise I agree about the overhead of course. It seems more of a bug in Github that it makes it appear that all checks have passed when not all checks have run.

**Comment by MarcoFalke** [comment]
I think we shouldn't put any trust in travis or GitHub. I am seeing data corruption of the metadata they pass around almost every week. Just a few issues of the last 5 days:

* travis reported green for an issue that is reproducibly failing according to https://github.com/bitcoin/bitcoin/pull/18376#issuecomment-600607726
* GitHub reporting incorrect mergable state: https://github.com/bitcoin/bitcoin/pull/17562#issuecomment-601426905
* ...

**Comment by MarcoFalke** [comment]
Closing for now due to inactivity

**Pull request closed without merging**
