### PR TITLE
github-merge: Add optional support for fetch_repo != push_repo

### PR DESCRIPTION
**Pull request by MarcoFalke**
Currently github-merge assumes that the fetch_repo is identical to the push_repo. This comes with several issues:

* The maintainer development fork is not updated on a merge, and the maintainer has to manually type `git push my_fork master` after each merge (if they wish so).
* github-merge is currently not suitable for a "Linux-style" monotree development style. Specifically it is not possible to merge a pull request that has been filed against a repository that is not `githubmerge.repository`.

Fix both issues by adding:

* (Done in #59) An optional push_mirrors config setting to push the master branch to more than just the main mirror. In action:

```
...
Type 's' to sign off on the above merge, or 'x' to reject and exit. s

Type 'push' to push the result to git@github.com:bitcoin/bitcoin, git@github.com:MarcoFalke/bitcoin-core.git, git@gitlab.com:anoter_owner/bitcoin-core.git, branch master, or 'x' to exit without pushing. 
```

* An optional run-time argument to specify a different fetch repo. In action:

```
github-merge.py --repo_from bitcoin-core/gui 1234

### CODE REVIEW

**Comment by MarcoFalke** [comment]
I will give some more background in the next meeting on Thursday hopefully

**Comment by MarcoFalke** [comment]
btw I've been using this version of the script for the last couple of weeks without issues.

Tested that gitlab and github mirrors are supported, as well as a monotree merge.

**Comment by MarcoFalke** [comment]
* While use of the patched script is not required for "pure" bitcoin/bitcoin maintainers, I recommend that every maintainer runs commit a6cb129 or later with the following setting:

```
$ git config githubmerge.pushmirrors
git@github.com:bitcoin-core/gui.git,git@github.com:MarcoFalke/bitcoin-core.git
```

In action it look as follows:

```
Type 's' to sign off on the above merge, or 'x' to reject and exit. s

Type 'push' to push the result to git@github.com:bitcoin/bitcoin, git@github.com:bitcoin-core/gui.git, git@github.com:MarcoFalke/bitcoin-core.git, branch master, or 'x' to exit without pushing. push

Enumerating objects: 44, done.
...
To github.com:bitcoin/bitcoin
   0afbeb73cc..4b30c41b4e  master -> master
Enumerating objects: 149672, done.
...
To github.com:bitcoin-core/gui.git
 * [new branch]            master -> master
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:MarcoFalke/bitcoin-core.git
   0afbeb73cc..4b30c41b4e  master -> master
```

* For merging gui pull request a version as of commit 6ab1003 is required, which adds support for `repo_from`.

**Comment by fanquake** [comment]
@MarcoFalke can you rebase this now that #59 is in.

**Comment by laanwj** [comment]
Concept ACK

**Pull request merged**
