### PR TITLE
github-merge: Add push_mirrors config setting

### PR DESCRIPTION
**Pull request by MarcoFalke**
Two refactoring commits and one feature commit. Fyi, my config looks like this:

```
$ git config githubmerge.pushmirrors
git@github.com:bitcoin-core/gui.git,git@github.com:MarcoFalke/bitcoin-core.git

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK. Looks ok. I take it this is the merge script you've been using in prod for the past couple months?

**Comment by MarcoFalke** [comment]
I am using #57 as the merge script, which includes the changes here

**Comment by MarcoFalke** [comment]
but yeah, it would help if the other maintainers were running this script with the push config. Otherwise, the gui monotree `https://github.com/bitcoin-core/gui` gets out of sync intermittently.

**Review by fanquake — APPROVED** [review]
ACK a8c9df3326a1f74e4ea22c290fd2574a5c58384b  - looks ok & leaving this as optional/non-default for now.

**Comment by MarcoFalke** [comment]
@laanwj / @fanquake would be good if at least one of you pushed to the gui mirror as well when merging. Otherwise I am the only one who keeps the gui repo in sync.

With the patched github-merge here, an additional push should only take a few more seconds.

**Pull request merged**
