### PR TITLE
github-merge: Show merge message if there are warnings

### PR DESCRIPTION
**Pull request by laanwj**
Show the merge message in case there are warnings. Highlight the symbols that caused the warning.

### CODE REVIEW

**Comment by jonatack** [comment]
Concept ACK, I can imagine this would be useful.

**Comment by laanwj** [comment]
Thanks!

Thinking of it, it'd make sense to strip out control characters before printing, so that the PR messages can't do potentially confusing or harmful things with ANSI formatting, linefeeds bells etc.

**Comment by jonatack** [comment]
Ooh, didn't try embedding bells yet. That would be fun.

**Comment by laanwj** [comment]
Might want to merge #70 first 😄

**Comment by laanwj** [comment]
Thinking of it, maybe it's more useful to *only* print the lines that have the "disallowed" characters, instead of the whole thing?

**Comment by jonatack** [comment]
Highlighting the bad parts seems like the practical aspect; maybe print all of it versus only the offending lines depending on the total length of the thing?

**Comment by laanwj** [comment]
Another option would be to do like grep — show a certain number of lines of context around an occurrence.

But I guess ideally merge messages wouldn't be that long, at all. If they're longer than a certain number of lines it might be reason to warn in itself :slightly_frowning_face:

**Comment by fanquake** [comment]
Concept ACK

**Review by RonSherfey — APPROVED** [review]

**Comment by laanwj** [comment]
Going ahead and merging this, if the large text dump becomes annoying we can always decide to only print a context.

**Pull request merged**
